Resources:
  MyTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: my-task-family
      ExecutionRoleArn: arn:aws:iam::134412166047:user/user-final
      NetworkMode: awsvpc
      ContainerDefinitions:
        - Name: my-container-1
          Image: phat99/capstone-engineer-cloud-hotanphat:latest
          Essential: true
          PortMappings:
            - ContainerPort: 8080
        - Name: my-container-2
          Image: other-image:latest
          Essential: true
          PortMappings:
            - ContainerPort: 8081
