# AWSTemplateFormatVersion: 2010-09-09

# Parameters:
#   ImageTag:
#     Type: String
#     Description: Tag of the Docker image to deploy in this stack
#     Default: latest

# Resources:
#   TaskDefMyApp:
#     Type: AWS::ECS::TaskDefinition
#     Properties:
#       Family: MyApp
#       ContainerDefinitions:
#         - Name: MyAppContainer
#           Memory: 512
#           Image: !Sub "134412166047.dkr.ecr.us-east-1.amazonaws.com/capstone-engineer-cloud-hotanphat:${ImageTag}"
#           PortMappings:
#             - ContainerPort: 80
#               Protocol: tcp

#   EC2Instance:
#     Type: AWS::EC2::Instance
#     Properties:
#       ImageId: ami-052fff77b3e2ecbca
#       InstanceType: t2.micro
#       KeyName: newkeypair
#       SecurityGroupIds:
#         - sg-0a5fabd50db5956a7
#       UserData:
#         Fn::Base64: |
#           #!/bin/bash
#           # Add any desired user data scripts for EC2 instance setup

#   DockerImage:
#     Type: AWS::ECR::Repository
#     Properties:
#       RepositoryName: capstone-engineer-cloud-hotanphat

# Outputs:
#   EC2InstanceId:
#     Value: !Ref EC2Instance

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: capstone-engineer-cloud-hotanphat
#   labels:
#     app: capstone-engineer-cloud-hotanphat
#   namespace: default
# spec:
#   replicas: 2
#   progressDeadlineSeconds: 3600
#   selector:
#     matchLabels:
#       app: capstone-engineer-cloud-hotanphat
#   strategy:
#     rollingUpdate:
#       maxSurge: 25%
#       maxUnavailable: 25%
#     type: RollingUpdate
#   template:
#     metadata:
#       labels:
#         app: uda-cap
#     spec:
#       containers:
#         - image: phat99/capstone-engineer-cloud-hotanphat
#           imagePullPolicy: Always
#           name: capstone-engineer-cloud-hotanphat
#           ports:
#             - containerPort: 80
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
  labels:
    app: capstone
spec:
  selector:
    matchLabels:
      app: capstone
  replicas: 3
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
        - name: app
          image: phat99/capstone_project:latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8080
