# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: phatfpt-capstone
#   labels:
#     app: phatfpt-capstone
#   namespace: default
# spec:
#   replicas: 2
#   progressDeadlineSeconds: 3600
#   selector:
#     matchLabels:
#       app: phatfpt-capstone
#   strategy:
#     rollingUpdate:
#       maxSurge: 25%
#       maxUnavailable: 25%
#     type: RollingUpdate
#   template:
#     metadata:
#       labels:
#         app: phatfpt-capstone
#     spec:
#       containers:
#         - image: phat99/phatfpt-capstone
#           imagePullPolicy: Always
#           name: phatfpt-capstone
#           ports:
#             - containerPort: 80

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: phatfpt-capstone
#   labels:
#     app: phatfpt-capstone
# spec:
#   type: LoadBalancer
#   selector:
#     app: phatfpt-capstone
#   ports:
#     - port: 80
#       targetPort: 80
#       protocol: TCP
Description: >
  CapStone Project stack.

Parameters:
  ID:
    Description: Unique identifier.
    Type: String

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub phatfpt-capstone-${ID}
      GroupDescription: Allow port 22 and port 80.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: capstone-deploy
      ImageId: ami-07dd19a7900a1f049
      Tags:
        - Key: Name
          Value: !Sub phatfpt-capstone-${ID}
