AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-bucket-name

  MyKubernetesDeployment:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: your-cluster-name
      NodegroupName: my-deployment
      ScalingConfig:
        DesiredSize: 3
        MaxSize: 3
        MinSize: 3
      Labels:
        app: capstone
      NodeRole: arn:aws:iam::123456789012:role/eks-nodegroup-role
      Subnets:
        - subnet-12345678
        - subnet-23456789
      LaunchTemplate:
        Name: my-launch-template
        Version: my-launch-template-version
      Overrides:
        - ContainerOverrides:
            - Name: app
              Image: phat99/capstone-engineer-cloud-hotanphat:latest
              Command:
                - /bin/bash
              ResourceRequirements:
                - Value:
                    cpu: "100m"
                    memory: "100Mi"
              PortMappings:
                - ContainerPort: 8080
