apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudformation-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudformation-stack
  template:
    metadata:
      labels:
        app: cloudformation-stack
    spec:
      containers:
        - name: aws-cli
          image: amazon/aws-cli:latest
          command: ["sleep", "infinity"]
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_secret_access_key
          volumeMounts:
            - name: aws-credentials
              mountPath: /root/.aws
      volumes:
        - name: aws-credentials
          secret:
            secretName: aws-credentials
