AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: my-ecr-repo

  udapeople-plaplapla: # Ensure this matches the logical ID of the existing S3 bucket resource
    Type: AWS::S3::Bucket
    Properties:
      BucketName: udapeople-plaplapla

  MyCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt udapeople-plaplapla.DomainName # Update the logical ID here
            Id: MyS3BucketOrigin
            S3OriginConfig:
              OriginAccessIdentity: ""
        DefaultRootObject: index.html
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: MyS3BucketOrigin
          ForwardedValues:
            QueryString: false
          ViewerProtocolPolicy: redirect-to-https

Outputs:
  ECRRepositoryName:
    Value: !Ref MyECRRepository
    Description: ECR repository name

  CloudFrontDistributionId:
    Value: !Ref MyCloudFrontDistribution
    Description: CloudFront distribution ID
