apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
        - name: capstone
          image: phat99/capstone-engineer-cloud-hotanphat:{{VERSION}}
          ports:
            - containerPort: 80
