apiVersion: apps/v1
kind: Deployment
metadata:
  name: phatfpt-capstone
  labels:
    app: phatfpt-capstone
  namespace: default
spec:
  replicas: 2
  progressDeadlineSeconds: 3600
  selector:
    matchLabels:
      app: phatfpt-capstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: phatfpt-capstone
    spec:
      containers:
        - command:
            - --authorization-mode=Node,RBAC
            - --advertise-address=10.200.200.100
            - --allow-privileged=true
            - --client-ca-file=/etc/kubernetes/pki/ca.crt
            - --disable-admission-plugins=PersistentVolumeLabel
            - --enable-admission-plugins=NodeRestriction
            - --enable-bootstrap-token-auth=true
            - --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt
            - --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt
            - --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key
            - --etcd-servers=https://127.0.0.1:2379
            - --insecure-port=0
            - --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt
            - --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key
            - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
            - --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt
            - --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key
            - --requestheader-allowed-names=front-proxy-client
            - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
            - --requestheader-extra-headers-prefix=X-Remote-Extra-
            - --requestheader-group-headers=X-Remote-Group
            - --requestheader-username-headers=X-Remote-User
            - --secure-port=6443
            - --service-account-key-file=/etc/kubernetes/pki/sa.pub
            - --service-cluster-ip-range=10.96.0.0/12
            - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
            - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
        - image: phat99/phatfpt-capstone
          imagePullPolicy: Always
          name: phatfpt-capstone
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: phatfpt-capstone
  labels:
    app: phatfpt-capstone
spec:
  type: LoadBalancer
  selector:
    app: phatfpt-capstone
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
