AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: eks_orb_capstone_project

  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: phatht-final-capstone-project

  MyCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt MyS3Bucket.DomainName
            Id: MyS3BucketOrigin
            S3OriginConfig:
              OriginAccessIdentity: ""
        DefaultRootObject: index.html
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: MyS3BucketOrigin
          ForwardedValues:
            QueryString: false
          ViewerProtocolPolicy: redirect-to-https

Outputs:
  ECRRepositoryName:
    Value: !Ref MyECRRepository
    Description: ECR repository name

  CloudFrontDistributionId:
    Value: !Ref MyCloudFrontDistribution
    Description: CloudFront distribution ID
