apiVersion: apps/v1
kind: Deployment
metadata:
  name: phatht8-capstone
  labels:
    app: phatht8-capstone
  namespace: default
spec:
  replicas: 2
  progressDeadlineSeconds: 3600
  selector:
    matchLabels:
      app: phatht8-capstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: phatht8-capstone
    spec:
      containers:
        - image: phat99/phatht8-capstone
          imagePullPolicy: Always
          name: phatht8-capstone
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: phatht8-capstone
  labels:
    app: phatht8-capstone
spec:
  type: LoadBalancer
  selector:
    app: phatht8-capstone
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
