version: 2.1

executors:
  python:
    docker:
      - image: circleci/python:3.7.3-stretch
  aws:
    docker:
      - image: amazon/aws-cli

jobs:
  lint-app:
    executor: python
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            sudo chmod +x /bin/hadolint
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint

  build-push-docker-image:
    machine: true
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: build and push docker image
          command: |
            #Login to docker hub
            docker login --username $DOCKERHUB_USER --password $DOCKERHUB_PWD
            # Build image and add a descriptive tag
            docker build --tag=phatht8-capstone .
            # List docker images
            docker image ls
            # Push image to a docker repository
            docker tag phatht8-capstone phat99/phatht8-capstone
            docker push phat99/phatht8-capstone

  deploy-to-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          phatht8-capstone
        type: string
    steps:
      - checkout
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          # get-rollout-status: true
          resource-file-path: deployment.yml
          resource-name: deployment/phatht8-capstone

  check-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          phatht8-capstone
        type: string
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - run:
          name: check cluster
          command: |
            kubectl get nodes
            kubectl get deployment

orbs:
  aws-eks: circleci/aws-eks@1.0.3
  kubernetes: circleci/kubernetes@0.11.2

workflows:
  deployment:
    jobs:
      - lint-app
      - build-push-docker-image:
          requires: [lint-app]
      - aws-eks/create-cluster:
          cluster-name: phatht8-capstone
      - deploy-to-cluster:
          cluster-name: phatht8-capstone
          requires: [aws-eks/create-cluster]
      - aws-eks/update-container-image:
          cluster-name: phatht8-capstone
          container-image-updates: phatht8-capstone=phat99/phatht8-capstone
          post-steps:
            - kubernetes/delete-resource:
                resource-names: phatht8-capstone
                resource-types: deployment
                wait: true
          record: true
          requires: [deploy-to-cluster]
          resource-name: deployment/phatht8-capstone
      - check-cluster:
          cluster-name: phatht8-capstone
          requires: [aws-eks/update-container-image]
      - aws-eks/delete-cluster:
          cluster-name: phatht8-capstone
          requires: [check-cluster]
