version: 2.1

executors:
  python:
    docker:
      - image: circleci/python:3.7.3-stretch
  aws:
    docker:
      - image: amazon/aws-cli

jobs:
  run-lint:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Install hadolint
          command: |
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
            sudo chmod +x /bin/hadolint
      - run:
          name: Run Lint
          command: |
            hadolint Dockerfile

  build-push-docker-image:
    machine: true
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: build and push docker image
          command: |
            #Login to docker hub
            docker login --username $DOCKERHUB_USER --password $DOCKERHUB_PWD
            # Build image and add a descriptive tag
            docker build --tag=uda-cap .
            # List docker images
            docker image ls
            # Push image to a docker repository
            docker tag uda-cap phat99/uda-cap
            docker push phat99/uda-cap

  deploy-to-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          uda-cap
        type: string
    steps:
      - checkout
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          # get-rollout-status: true
          resource-file-path: cloudformation/cloudformation.yml
          resource-name: deployment/uda-cap

  check-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          uda-cap
        type: string
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - run:
          name: check cluster
          command: |
            kubectl get nodes
            kubectl get deployment

orbs:
  aws-eks: circleci/aws-eks@1.0.3
  kubernetes: circleci/kubernetes@0.11.2

workflows:
  deployment:
    jobs:
      - run-lint
      - build-push-docker-image:
          requires: [run-lint]
      - aws-eks/create-cluster:
          cluster-name: uda-cap
      - deploy-to-cluster:
          cluster-name: uda-cap
          requires: [aws-eks/create-cluster]
      - aws-eks/update-container-image:
          cluster-name: uda-cap
          container-image-updates: uda-cap=phat99/uda-cap
          post-steps:
            - kubernetes/delete-resource:
                resource-names: uda-cap
                resource-types: deployment
                wait: true
          record: true
          requires: [deploy-to-cluster]
          resource-name: deployment/uda-cap
      - check-cluster:
          cluster-name: uda-cap
          requires: [aws-eks/update-container-image]
      - aws-eks/delete-cluster:
          cluster-name: uda-cap
          requires: [check-cluster]
