version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      # Install AWS CLI
      - run:
          name: Install AWS CLI
          command: |
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws

      # Authenticate with AWS ECR
      - run:
          name: Authenticate ECR
          command: |
            aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin 134412166047.dkr.ecr.us-east-1.amazonaws.com

      # Build and push Docker image to ECR
      - run:
          name: Build and Push Docker Image
          command: |
            export TAG="v1.${CIRCLE_BUILD_NUM}"
            docker build -t 134412166047.dkr.ecr.us-east-1.amazonaws.com/eks_orb_capstone_project:$TAG .
            docker push 134412166047.dkr.ecr.us-east-1.amazonaws.com/eks_orb_capstone_project:$TAG

      # Deploy CloudFormation stack
      - run:
          name: Deploy CloudFormation Stack
          command: |
            aws cloudformation deploy --region ${AWS_DEFAULT_REGION} --stack-name capstone-project --template-file deployments/deployment.yml --capabilities CAPABILITY_IAM

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
