version: 2.1

orbs:
  kubernetes: circleci/kubernetes@0.13.0

jobs:
  deploy-cloudformation:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Install AWS CLI and authenticate
          command: |
            sudo apt-get install -y awscli
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_DEFAULT_REGION
      - kubernetes/install-kubectl:
          version: v1.22.0
      - run:
          name: Apply Kubernetes Deployment
          command: |
            kubectl apply -f deployment.yml

workflows:
  version: 2
  deploy-cloudformation:
    jobs:
      - deploy-cloudformation
