version: 2.1

orbs:
  aws-eks: circleci/aws-eks@2.2.0
  aws-ecr: circleci/aws-ecr@3.1.0
  aws-cli: circleci/aws-cli@1.4.0
  kubernetes: circleci/kubernetes@1.3.1
executors:
  aws-eks/linux-machine:
    machine:
      image: ubuntu-2004:202106-01

jobs:
  run-lint:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Install hadolint
          command: |
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
            sudo chmod +x /bin/hadolint
      - run:
          name: Run Lint
          command: |
            hadolint Dockerfile

  build-push-docker-image:
    machine: true
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: build and push docker image
          command: |
            #Login to docker hub
            docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
            # Build image and add a descriptive tag
            docker build --tag=phatfpt-capstone-final-project .
            # List docker images
            docker image ls
            # Push image to a docker repository
            docker tag phatfpt-capstone-final-project phat99/phatfpt-capstone-final-project
            docker push phat99/phatfpt-capstone-final-project

  deploy-to-cluster:
    docker:
      - image: cimg/python:3.10
    parameters:
      cluster-name:
        description: |
          phatfpt-capstone-final-project
        type: string
    steps:
      - checkout
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          # get-rollout-status: true
          resource-file-path: deployments/deployment.yml
          resource-name: deployment/phatfpt-capstone-final-project

  check-cluster:
    docker:
      - image: cimg/python:3.10
    parameters:
      cluster-name:
        description: |
          phatfpt-capstone-final-project
        type: string
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - run:
          name: check cluster
          command: |
            kubectl get nodes
            kubectl get deployment

workflows:
  deployment:
    jobs:
      - run-lint
      - build-push-docker-image:
          requires: [run-lint]
      - aws-eks/create-cluster:
          cluster-name: eks-demo-deployment
      - deploy-to-cluster:
          cluster-name: phatfpt-capstone-final-project
          requires: [aws-eks/create-cluster]
      - aws-eks/update-container-image:
          cluster-name: phatfpt-capstone-final-project
          container-image-updates: phatfpt-capstone-final-project=phat99/phatfpt-capstone-final-project
          post-steps:
            - kubernetes/delete-resource:
                resource-names: phatfpt-capstone-final-project
                resource-types: deployment
                wait: true
          requires: [deploy-to-cluster]
          resource-name: deployment/phatfpt-capstone-final-project
      - check-cluster:
          cluster-name: phatfpt-capstone-final-project
          requires: [aws-eks/update-container-image]
      - aws-eks/delete-cluster:
          cluster-name: phatfpt-capstone-final-project
          requires: [check-cluster]
