apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: phatht8-casptone
data:
  mapRoles: |
    - rolearn: arn:aws:eks:us-east-1:134412166047:cluster/phatht8-casptone
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
