apiVersion: apps/v1
kind: Deployment
metadata:
  name: phatht8-casptone
  labels:
    app: phatht8-casptone
  namespace: default
spec:
  progressDeadlineSeconds: 3600
  replicas: 1
  selector:
    matchLabels:
      app: phatht8-casptone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: phatht8-casptone
    spec:
      containers:
        - image: phat99/phatht8-casptone:latest
          imagePullPolicy: Always
          name: phatht8-casptone
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "128Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: phatht8-casptone
  labels:
    app: phatht8-casptone
spec:
  type: LoadBalancer
  selector:
    app: phatht8-casptone
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP
